### ISSUE TITLE
Add TnbCrow Price

### ISSUE THREAD

**Issue by tomijaga** [open-blockchain-explorer/Website#30]
Add the price from the tnbCrow API to the network stats on the website 
http://crowapi.pythonanywhere.com/swagger/

![image](https://user-images.githubusercontent.com/50385769/123514906-1d957900-d68d-11eb-935b-5783a50cc446.png)

**Comment by hussu010** [comment]
Hi @tomijaga, we're hosting the price API here atm: https://tnbcrow.pythonanywhere.com/statistics

**Comment by tomijaga** [comment]
@hussu010 Do you also have an API for a list of transactions

**Comment by hussu010** [comment]
You could check the recent trades API. The endpoint is available on the
website footer.
