### ISSUE TITLE
Update Tnb Analytics data from csv to Json

### ISSUE THREAD

**Issue by tomijaga** [open-blockchain-explorer/Website#35]

**Comment by itsnikhil** [comment]
@tomijaga until we come up with some way which can scale, please use the following to make some of the data dynamic
- Rich list: https://raw.githubusercontent.com/itsnikhil/tnb-analysis/master/web/js/richlist.json 
- Header data: https://raw.githubusercontent.com/itsnikhil/tnb-analysis/master/web/js/static.json

**Comment by itsnikhil** [comment]
Stats API is live. Please see the following postman collection for API documentation
https://documenter.getpostman.com/view/12623083/U16qKP8S#6ae174e3-f2da-40ab-baae-09709c9e3c47
